name: orders
services:
  app:
    image: orders-multistage
    ports:
      - "8080:8080"
  db:
    image: postgres:16.4-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    profiles: ["db"]
  adminer:
    image: adminer:4.8.1
    ports:
      - "8081:8080"
    profiles: ["debug"]
    depends_on:
      - db
